name: Deploy Story Service

on:
  push:
    branches:
      - prod
    paths:
      - "story-service/**"
      - "!**/README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y publicar imagen Docker de Story Service
        uses: docker/build-push-action@v5
        with:
          context: ./story-service
          file: ./story-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/story-service:latest
